# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170628_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Days'),
        ),
        migrations.AlterField(
            model_name='package',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Gallery'),
        ),
        migrations.AlterField(
            model_name='package',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Place'),
        ),
        migrations.AlterField(
            model_name='package',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Season'),
        ),
    ]
