# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170705_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='photo',
            new_name='file',
        ),
    ]
