# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170705_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='fileType',
            field=models.PositiveIntegerField(choices=[(1, 'Photo'), (2, 'Video')], default=1),
        ),
    ]
