# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_slider_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='link',
        ),
        migrations.AddField(
            model_name='trailer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
